spring.application.name=discovery-server


server.port=8761

# Registry khud ko register nahi karegi
eureka.client.register-with-eureka=false

# Registry ko kisi doosri registry se data nahi chahiye
eureka.client.fetch-registry=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=health,info
